# Generated by Django 2.2.6 on 2019-11-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('mr', 'Mister'), ('mrs', 'Misses'), ('ms', 'Miss'), ('dr', 'Doctor'), ('prof', 'Professor')], default='not specified', max_length=30, verbose_name='Title')),
                ('initials', models.CharField(max_length=10, verbose_name='Initials')),
                ('surnames', models.CharField(max_length=100, verbose_name='Surname')),
                ('names', models.CharField(max_length=100, verbose_name='Names')),
                ('known_as', models.CharField(blank=True, max_length=50, null=True, verbose_name='Known As')),
                ('sa_id', models.BigIntegerField(verbose_name='RSA ID Number')),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Number')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='RatesAndReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('inflation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Inflation')),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Interest')),
                ('return_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Return Rate')),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientDetail')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation')),
                ('years_employed', models.IntegerField(blank=True, null=True, verbose_name='Years Employed')),
                ('personnel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation')),
                ('medical_aid', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5, verbose_name='Medical Aid')),
                ('retirement_fund_current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Retirement Fund Current Value')),
                ('group_life_cover', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5, verbose_name='Group Life Cover')),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientDetail')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('names', models.CharField(max_length=100, verbose_name='Surname')),
                ('surnames', models.CharField(max_length=100, verbose_name='Names')),
                ('rsa_resident', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=5, verbose_name='RSA Resident')),
                ('id_no', models.IntegerField(verbose_name='RSA ID Number')),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('father_in_law', 'Father-in-Law'), ('mother_in_law', 'Mother-in-Law'), ('other', 'Other')], default='not specified', max_length=50, verbose_name='Relationship')),
                ('other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other')),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientDetail')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('telephone_home', models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Telephone Number')),
                ('telephone_work', models.CharField(blank=True, max_length=10, null=True, verbose_name='Work Telephone Number')),
                ('cellphone_number', models.CharField(max_length=10, verbose_name='Cellphone Number')),
                ('fax_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax Number')),
                ('email_address', models.CharField(max_length=50, verbose_name='Email Address')),
                ('residential_address_line_1', models.CharField(max_length=100, verbose_name='Residential Address 1')),
                ('residential_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Residential Address 2')),
                ('residential_code', models.IntegerField(verbose_name='Residential Code')),
                ('postal_address_line_1', models.CharField(max_length=100, verbose_name='Initials')),
                ('postal_address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Initials')),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
                ('client_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientDetail')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
    ]
