# Generated by Django 4.2 on 2023-04-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "last_date_email",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last date email",
                    ),
                ),
                (
                    "last_date_sms",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last date SMS",
                    ),
                ),
                (
                    "last_date_call",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last date call",
                    ),
                ),
                (
                    "last_date_face_to_face",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last date face to face",
                    ),
                ),
                (
                    "last_contacted",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last date contacted",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientCommunicationFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("face_to_face_frequency", models.IntegerField(blank=True, null=True)),
                ("calls_frequency", models.IntegerField(blank=True, null=True)),
                ("email_frequency", models.IntegerField(blank=True, null=True)),
                ("sms_frequency", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientContactDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "telephone_home",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Home Telephone Number",
                    ),
                ),
                (
                    "telephone_work",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Work Telephone Number",
                    ),
                ),
                (
                    "cellphone_number",
                    models.CharField(max_length=10, verbose_name="Cellphone Number"),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Fax Number"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=50, verbose_name="Email Address"),
                ),
                (
                    "residential_address_line_1",
                    models.CharField(max_length=100, verbose_name="Street Address"),
                ),
                (
                    "residential_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Apt, Suite, Building or Company Name (Optional)",
                    ),
                ),
                (
                    "residential_suburb",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Suburb"
                    ),
                ),
                (
                    "residential_city",
                    models.CharField(max_length=100, verbose_name="City"),
                ),
                (
                    "residential_country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                ("residential_code", models.IntegerField(verbose_name="Postal Code")),
                (
                    "postal_address_line_1",
                    models.CharField(max_length=100, verbose_name="Street Address"),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Apt, Suite, Building or Company Name (Optional)",
                    ),
                ),
                (
                    "postal_suburb",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Suburb"
                    ),
                ),
                (
                    "postal_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postal City",
                    ),
                ),
                (
                    "postal_country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                ("postal_code", models.IntegerField(verbose_name="Postal Code")),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mister"),
                            ("mrs", "Misses"),
                            ("ms", "Miss"),
                            ("dr", "Doctor"),
                            ("prof", "Professor"),
                        ],
                        default="not specified",
                        max_length=30,
                        verbose_name="Title",
                    ),
                ),
                ("initials", models.CharField(max_length=10, verbose_name="Initials")),
                ("surnames", models.CharField(max_length=100, verbose_name="Surname")),
                ("names", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "known_as",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Known As"
                    ),
                ),
                (
                    "sa_id",
                    models.BigIntegerField(unique=True, verbose_name="RSA ID Number"),
                ),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advisor_email",
                    models.EmailField(
                        max_length=50, verbose_name="Advisor Email Address"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mister"),
                            ("mrs", "Misses"),
                            ("ms", "Miss"),
                            ("dr", "Doctor"),
                            ("prof", "Professor"),
                        ],
                        default="not specified",
                        max_length=30,
                        verbose_name="Title",
                    ),
                ),
                ("initials", models.CharField(max_length=10, verbose_name="Initials")),
                ("surnames", models.CharField(max_length=100, verbose_name="Surname")),
                ("names", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "known_as",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Known As"
                    ),
                ),
                ("sa_id", models.BigIntegerField(verbose_name="RSA ID Number")),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=50, verbose_name="Company Name"),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Occupation"
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
                (
                    "medical_aid",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                        verbose_name="Medical Aid",
                    ),
                ),
                (
                    "retirement_fund_current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Retirement Fund Current Value",
                    ),
                ),
                (
                    "group_life_cover",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                        verbose_name="Group Life Cover",
                    ),
                ),
                (
                    "telephone_home",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Home Telephone Number",
                    ),
                ),
                (
                    "telephone_work",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Work Telephone Number",
                    ),
                ),
                (
                    "cellphone_number",
                    models.CharField(max_length=10, verbose_name="Cellphone Number"),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Fax Number"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=50, verbose_name="Email Address"),
                ),
                (
                    "residential_address_line_1",
                    models.CharField(
                        max_length=100, verbose_name="Residential Address Line 1"
                    ),
                ),
                (
                    "residential_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Residential Address Line 2",
                    ),
                ),
                (
                    "residential_code",
                    models.IntegerField(verbose_name="Residential Code"),
                ),
                (
                    "postal_address_line_1",
                    models.CharField(
                        max_length=100, verbose_name="Postal Address Line 1"
                    ),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postal Addres Line 2",
                    ),
                ),
                ("postal_code", models.IntegerField(verbose_name="Postal Code")),
            ],
        ),
        migrations.CreateModel(
            name="ClientNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Note Title")),
                ("body", models.TextField(verbose_name="Note")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("comms", "Communications"),
                            ("preferences", "Preferences"),
                            ("archive", "Archive"),
                        ],
                        default="Note",
                        max_length=50,
                        verbose_name="Note Type",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("names", models.CharField(max_length=100, verbose_name="Name")),
                ("surnames", models.CharField(max_length=100, verbose_name="Surname")),
                (
                    "rsa_resident",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        max_length=5,
                        verbose_name="RSA Resident",
                    ),
                ),
                ("id_no", models.IntegerField(verbose_name="RSA ID Number")),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandfather", "Grandfather"),
                            ("grandmother", "Grandmother"),
                            ("father_in_law", "Father-in-Law"),
                            ("mother_in_law", "Mother-in-Law"),
                            ("other", "Other"),
                        ],
                        default="not specified",
                        max_length=50,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Other"
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmploymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(max_length=50, verbose_name="Company Name"),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Occupation"
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(
                        default="2018-01-01", verbose_name="Employment Date"
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
                (
                    "medical_aid",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                        verbose_name="Medical Aid",
                    ),
                ),
                (
                    "retirement_fund_current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Retirement Fund Current Value",
                    ),
                ),
                (
                    "group_life_cover",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=5,
                        verbose_name="Group Life Cover",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RatesAndReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "inflation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Inflation",
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Interest",
                    ),
                ),
                (
                    "return_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Return Rate",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
