# Generated by Django 2.2.6 on 2020-05-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('practises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='advisor_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practises.AdvisorDetail'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='clientdetail',
            order_with_respect_to='created_at',
        ),
        migrations.AddField(
            model_name='clientcontactdetail',
            name='client_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientDetail'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='clientcontactdetail',
            order_with_respect_to='created_at',
        ),
    ]
