# Generated by Django 2.2.6 on 2019-11-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetail",
            name="surnames",
            field=models.CharField(max_length=100, verbose_name="Surnames"),
        ),
    ]
