# Generated by Django 4.2 on 2023-04-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("practises", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ratesandreturn",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="ratesandreturn",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="employmentdetail",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="employmentdetail",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="dependent",
            name="client_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="clients.clientdetail",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="dependent",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="client_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.clientdetail"
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="clientproduct",
            name="product_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="practises.productdetail",
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientproduct",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientnote",
            name="client_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="clients.clientdetail",
            ),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientnote",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="advisor_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="practises.advisordetail",
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="client_comms_fk",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="clients.clientcommunication",
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="client_comms_freq_fk",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.clientcommunicationfrequency",
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="client_contact_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.clientcontactdetail",
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="client_employment_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.employmentdetail",
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="client_rates_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.ratesandreturn"
            ),
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientdetail",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientcontactdetail",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientcommunicationfrequency",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientcommunicationfrequency",
            order_with_respect_to="created_at",
        ),
        migrations.AddField(
            model_name="clientcommunication",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterOrderWithRespectTo(
            name="clientcommunication",
            order_with_respect_to="created_at",
        ),
    ]
