# Generated by Django 2.2.6 on 2020-06-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_auto_20200531_1725"),
    ]

    operations = [
        migrations.RemoveField(model_name="clientcontactdetail", name="client_id_fk",),
        migrations.AddField(
            model_name="clientdetail",
            name="client_contact_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.ClientContactDetail",
            ),
            preserve_default=False,
        ),
    ]
