# Generated by Django 2.2.6 on 2020-04-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0002_auto_20191208_1233"),
        ("clients", "0005_auto_20191128_1730"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactDetail", new_name="ClientContactDetail",
        ),
        migrations.AddField(
            model_name="clientdetail",
            name="advisor_id_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="practises.AdvisorDetail",
            ),
            preserve_default=False,
        ),
    ]
