# Generated by Django 2.2.13 on 2020-06-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_auto_20200605_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetail",
            name="advisor_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="practises.AdvisorDetail",
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="client_id_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="clients.ClientDetail",
            ),
        ),
    ]
