# Generated by Django 2.2.6 on 2020-06-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20200613_1345'),
        ('clients', '0009_auto_20200613_1045'),
    ]

    operations = [
    ]
