# Generated by Django 2.2.13 on 2020-06-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0012_clientnote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientnote", old_name="note", new_name="body",
        ),
        migrations.RenameField(
            model_name="clientnote", old_name="header", new_name="title",
        ),
        migrations.AddField(
            model_name="clientnote",
            name="client_id_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="clients.ClientDetail",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientnote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("follow_up", "Follow Up"),
                    ("do_not_mention", "Do Not Mention"),
                    ("mention", "Mention"),
                    ("archive", "Archive"),
                ],
                default="Note",
                max_length=50,
                verbose_name="Note Type",
            ),
        ),
    ]
