# Generated by Django 2.2.13 on 2020-06-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0013_auto_20200623_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientnote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("follow_up", "Follow Up"),
                    ("do_not_mention", "Do Not Mention"),
                    ("preferences", "Preferences"),
                    ("archive", "Archive"),
                ],
                default="Note",
                max_length=50,
                verbose_name="Note Type",
            ),
        ),
        migrations.AlterField(
            model_name="clientnote",
            name="title",
            field=models.CharField(
                blank=True,
                default="2020-06-23 06:29:22.842548",
                max_length=100,
                null=True,
                verbose_name="Note Title",
            ),
        ),
    ]
