# Generated by Django 2.2.13 on 2020-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0014_clientnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientnote",
            name="body",
            field=models.TextField(verbose_name="Note"),
        ),
    ]
