# Generated by Django 2.2.13 on 2020-07-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_auto_20200701_1012"),
        ("clients", "0015_auto_20200629_2239"),
    ]

    operations = []
