# Generated by Django 2.2.13 on 2020-07-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0016_merge_20200703_2132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetail",
            name="client_comms_fk",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="clients.ClientCommunication",
            ),
        ),
    ]
