# Generated by Django 2.2.13 on 2020-11-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_auto_20200812_0218"),
        ("clients", "0018_clientproduct"),
    ]

    operations = []
