# Generated by Django 2.2.13 on 2020-11-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clientproduct'),
        ('clients', '0017_auto_20200812_0218'),
    ]

    operations = [
    ]
