# Generated by Django 2.2.13 on 2020-10-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20200812_0218'),
        ('clients', '0018_clientproduct'),
    ]

    operations = [
    ]
