# Generated by Django 2.2.13 on 2021-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_merge_20201111_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='sa_id',
            field=models.BigIntegerField(unique=True, verbose_name='RSA ID Number'),
        ),
    ]
