# Generated by Django 2.2.13 on 2020-12-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_merge_20201111_1820"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontactdetail",
            name="postal_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Postal City"
            ),
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="postal_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Postal Country"
            ),
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="postal_suburb",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Postal Suburb"
            ),
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="residential_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Residential City"
            ),
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="residential_country",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Country",
            ),
        ),
        migrations.AddField(
            model_name="clientcontactdetail",
            name="residential_suburb",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Residential Suburb"
            ),
        ),
    ]
