# Generated by Django 2.2.13 on 2021-02-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_auto_20201229_2312"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcommunication",
            name="last_contacted",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Last date contacted"
            ),
        ),
    ]
