# Generated by Django 2.2.13 on 2021-03-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20210128_1719'),
        ('clients', '0021_auto_20210209_2326'),
    ]

    operations = [
    ]
