# Generated by Django 2.2.13 on 2021-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_merge_20210308_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="postal_address_line_1",
            field=models.CharField(max_length=100, verbose_name="Street Address"),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="postal_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Apt, Suite, Building or Company Name (Optional)",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="postal_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="postal_suburb",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Suburb"
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_address_line_1",
            field=models.CharField(max_length=100, verbose_name="Street Address"),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Apt, Suite, Building or Company Name (Optional)",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_city",
            field=models.CharField(default="test", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_code",
            field=models.IntegerField(verbose_name="Postal Code"),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="clientcontactdetail",
            name="residential_suburb",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Suburb"
            ),
        ),
        migrations.AlterField(
            model_name="clientimport",
            name="postal_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Postal Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="clientimport",
            name="postal_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Postal Addres Line 2",
            ),
        ),
        migrations.AlterField(
            model_name="clientimport",
            name="residential_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Residential Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="clientimport",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Address Line 2",
            ),
        ),
    ]
