---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ayama
    run: ayama-redis
  name: ayama-redis
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: ayama
      run: ayama-redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: "ayama-redis"
        app: ayama
    spec:
      containers:
        - image: redis:5.0.5-alpine
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ayama
  name: ayama-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: ayama
    run: ayama-redis
  type: ClusterIP