version: '3.8'

services:
  ayama:
    image: figly-crm-ayama:latest
    depends_on:
      - postgres
    env_file: ../.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - LOG_LEVEL=debug
    ports:
      - 8080:8080

  migrate:
    image: figly-crm-ayama:latest
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    command: [ "python", "manage.py", "migrate" ]
