# Generated by Django 2.2.6 on 2019-11-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PractiseDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Practise Name"),
                ),
                (
                    "residential_address_line_1",
                    models.CharField(
                        max_length=100, verbose_name="Residential Address 1"
                    ),
                ),
                (
                    "residential_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Residential Address 2",
                    ),
                ),
                (
                    "residential_code",
                    models.IntegerField(verbose_name="Residential Code"),
                ),
                (
                    "postal_address_line_1",
                    models.CharField(max_length=100, verbose_name="Postal Address 1"),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postal Address 2",
                    ),
                ),
                ("postal_code", models.IntegerField(verbose_name="Postal Code")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
                ("employment_date", models.DateField(verbose_name="Employment Date")),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
        migrations.CreateModel(
            name="AdvisorDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mister"),
                            ("mrs", "Misses"),
                            ("ms", "Miss"),
                            ("dr", "Doctor"),
                            ("prof", "Professor"),
                        ],
                        default="not specified",
                        max_length=30,
                        verbose_name="Title",
                    ),
                ),
                ("initials", models.CharField(max_length=10, verbose_name="Initials")),
                ("surnames", models.CharField(max_length=100, verbose_name="Surnames")),
                ("names", models.CharField(max_length=100, verbose_name="Names")),
                (
                    "known_as",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Known As"
                    ),
                ),
                ("sa_id", models.BigIntegerField(verbose_name="RSA ID Number")),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
                ("employment_date", models.DateField(verbose_name="Employment Date")),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
                (
                    "practise_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.PractiseDetail",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
        migrations.CreateModel(
            name="AdvisorContactDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "telephone_home",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Home Telephone Number",
                    ),
                ),
                (
                    "telephone_work",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Work Telephone Number",
                    ),
                ),
                (
                    "cellphone_number",
                    models.CharField(max_length=10, verbose_name="Cellphone Number"),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Fax Number"
                    ),
                ),
                (
                    "email_address",
                    models.CharField(max_length=50, verbose_name="Email Address"),
                ),
                (
                    "residential_address_line_1",
                    models.CharField(
                        max_length=100, verbose_name="Residential Address 1"
                    ),
                ),
                (
                    "residential_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Residential Address 2",
                    ),
                ),
                (
                    "residential_code",
                    models.IntegerField(verbose_name="Residential Code"),
                ),
                (
                    "postal_address_line_1",
                    models.CharField(max_length=100, verbose_name="Postal Address 1"),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postal Address 2",
                    ),
                ),
                ("postal_code", models.IntegerField(verbose_name="Postal Code")),
                (
                    "advisor_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.AdvisorDetail",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
        migrations.CreateModel(
            name="AdministratorDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mister"),
                            ("mrs", "Misses"),
                            ("ms", "Miss"),
                            ("dr", "Doctor"),
                            ("prof", "Professor"),
                        ],
                        default="not specified",
                        max_length=30,
                        verbose_name="Title",
                    ),
                ),
                ("initials", models.CharField(max_length=10, verbose_name="Initials")),
                ("surnames", models.CharField(max_length=100, verbose_name="Surnames")),
                ("names", models.CharField(max_length=100, verbose_name="Names")),
                (
                    "known_as",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Known As"
                    ),
                ),
                ("sa_id", models.BigIntegerField(verbose_name="RSA ID Number")),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Passport Number",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
                ("employment_date", models.DateField(verbose_name="Employment Date")),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
                (
                    "advisor_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.AdvisorDetail",
                    ),
                ),
                (
                    "practise_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.PractiseDetail",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
        migrations.CreateModel(
            name="AdministratorContactDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "telephone_home",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Home Telephone Number",
                    ),
                ),
                (
                    "telephone_work",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Work Telephone Number",
                    ),
                ),
                (
                    "cellphone_number",
                    models.CharField(max_length=10, verbose_name="Cellphone Number"),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Fax Number"
                    ),
                ),
                (
                    "email_address",
                    models.CharField(max_length=50, verbose_name="Email Address"),
                ),
                (
                    "residential_address_line_1",
                    models.CharField(
                        max_length=100, verbose_name="Residential Address 1"
                    ),
                ),
                (
                    "residential_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Residential Address 2",
                    ),
                ),
                (
                    "residential_code",
                    models.IntegerField(verbose_name="Residential Code"),
                ),
                (
                    "postal_address_line_1",
                    models.CharField(max_length=100, verbose_name="Postal Address 1"),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Postal Address 2",
                    ),
                ),
                ("postal_code", models.IntegerField(verbose_name="Postal Code")),
                (
                    "adminstrator_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.AdministratorDetail",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
    ]
