# Generated by Django 2.2.6 on 2019-12-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="practisedetail", name="employment_date",),
        migrations.RemoveField(model_name="practisedetail", name="personnel_number",),
        migrations.RemoveField(model_name="practisedetail", name="position",),
    ]
