# Generated by Django 2.2.13 on 2020-06-18 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practises', '0005_auto_20200613_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorReminderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('face_to_face_frequency', models.IntegerField(blank=True, default=5, null=True)),
                ('calls_frequency', models.IntegerField(blank=True, default=5, null=True)),
                ('email_frequency', models.IntegerField(blank=True, default=5, null=True)),
                ('sms_frequency', models.IntegerField(blank=True, default=5, null=True)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'order_with_respect_to': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='advisordetail',
            name='reminder_config_freq_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practises.AdvisorReminderConfig'),
            preserve_default=False,
        ),
    ]
