# Generated by Django 2.2.13 on 2020-06-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practises', '0006_auto_20200618_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisordetail',
            name='reminder_config_freq_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to='practises.AdvisorReminderConfig'),
        ),
    ]
