# Generated by Django 2.2.13 on 2020-07-01 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0007_auto_20200618_2110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisordetail",
            name="practise_id_fk",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Advisors",
                to="practises.PractiseDetail",
            ),
        ),
    ]
