# Generated by Django 2.2.13 on 2020-08-12 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0008_auto_20200701_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisordetail",
            name="practise_id_fk",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Advisors",
                to="practises.PractiseDetail",
            ),
        ),
    ]
