# Generated by Django 2.2.13 on 2020-07-16 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0008_auto_20200701_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisordetail",
            name="practise_id_fk",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Advisors",
                to="practises.PractiseDetail",
            ),
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("INS", "Insurance"),
                            ("RA", "Retirement Annuity"),
                            ("UT", "Unit Trust"),
                        ],
                        default="not specified",
                        max_length=30,
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="Product Name"),
                ),
                (
                    "product_company",
                    models.CharField(max_length=100, verbose_name="Product Company"),
                ),
                ("is_active", models.BooleanField(verbose_name="Is Active")),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practises.PractiseDetail",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created_at",
                "abstract": False,
                "order_with_respect_to": "created_at",
            },
        ),
    ]
