# Generated by Django 2.2.13 on 2020-07-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0009_auto_20200716_2217"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdetail", old_name="practise", new_name="practise_id_fk",
        ),
    ]
