# Generated by Django 2.2.13 on 2020-10-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practises', '0010_auto_20200716_2243'),
        ('practises', '0009_auto_20200812_0218'),
    ]

    operations = [
    ]
