# Generated by Django 2.2.13 on 2020-11-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0009_auto_20200812_0218"),
        ("practises", "0010_auto_20200716_2243"),
    ]

    operations = []
