# Generated by Django 2.2.13 on 2021-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0012_auto_20201229_2312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administratorcontactdetail",
            name="residential_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Residential Address line 1"
            ),
        ),
        migrations.AlterField(
            model_name="administratorcontactdetail",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Address line 2",
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="postal_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Postal Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="postal_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Postal Address Line 2",
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="residential_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Residential Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Address Line 2",
            ),
        ),
    ]
