# Generated by Django 2.2.13 on 2021-02-16 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0012_auto_20201229_2312"),
    ]

    operations = [
        migrations.RemoveField(model_name="advisordetail", name="employment_date",),
        migrations.RemoveField(model_name="advisordetail", name="personnel_number",),
        migrations.RemoveField(model_name="advisordetail", name="position",),
        migrations.AlterField(
            model_name="administratorcontactdetail",
            name="residential_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Residential Address line 1"
            ),
        ),
        migrations.AlterField(
            model_name="administratorcontactdetail",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Address line 2",
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="postal_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Postal Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="postal_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Postal Address Line 2",
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="residential_address_line_1",
            field=models.CharField(
                max_length=100, verbose_name="Residential Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="advisorcontactdetail",
            name="residential_address_line_2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Residential Address Line 2",
            ),
        ),
        migrations.CreateModel(
            name="AdvisorEmploymentDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
                ("employment_date", models.DateField(verbose_name="Employment Date")),
                (
                    "personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Personnel Number",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"get_latest_by": "created_at", "abstract": False},
        ),
        migrations.RunSQL(
            "INSERT INTO practises_advisoremploymentdetail (created_at ,modified_at, position,personnel_number,employment_date, modified_by_id) VALUES ('2020-01-01','2020-01-01', 'Test','1', '2020-01-01',2);"
        ),
        migrations.AddField(
            model_name="advisordetail",
            name="advisor_employment_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="practises.AdvisorEmploymentDetail",
            ),
            preserve_default=False,
        ),
    ]
