# Generated by Django 2.2.13 on 2021-03-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practises', '0013_auto_20210209_2323'),
        ('practises', '0013_auto_20210216_2233'),
    ]

    operations = [
    ]
