# Generated by Django 2.2.13 on 2021-05-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0016_auto_20210429_2148"),
    ]

    operations = [
        migrations.RemoveField(model_name="productadvisor", name="product_id_fk",),
        migrations.AddField(
            model_name="productadvisor",
            name="product_id_fk",
            field=models.ManyToManyField(to="practises.ProductDetail"),
        ),
    ]
