# Generated by Django 2.2.13 on 2021-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practises", "0017_auto_20210506_2350"),
    ]

    operations = [
        migrations.RemoveField(model_name="productclient", name="product_id_fk",),
        migrations.AddField(
            model_name="productclient",
            name="product_id_fk",
            field=models.ManyToManyField(to="practises.ProductDetail"),
        ),
    ]
